import React from 'react'
import { FiHome } from 'react-icons/fi'
import { IoIosArrowForward } from 'react-icons/io'

const TermsOfUse = () => {
    return (
        <div className='container'>
            <div className='flex items-center gap-2 text-sm text-black/50 mb-4'>
                <a href="/" className='text-black/50'>Home</a>
                <IoIosArrowForward />
                <span>Terms of use</span>
            </div>

            <div className='relative mb-5'>
                <img src="/assets/images/png/policy.png" alt="about" />
                <h1 className='md:text-[28px] text-white text-[24px] absolute top-0 flex items-center justify-center w-full h-full'>Terms of use</h1>
            </div>

            <h1 className="md:text-[28px] text-[24px] mb-4">Terms of use</h1>
            <p className='text-black/50 leading-[30px]'>Your terms and conditions, outlining how users can engage with your website or services.</p>
            <p className='text-black/50 leading-[30px]'>Welcome to Sportzcraazy. This domain bearing name; www.sportzcraazy.com is owned by Sportzcraazy Technologies Private Limited, a company incorporated under the Companies Act, 1956 and having its registered address at, D29-2nd Floor, GK -II Enclave, Opp. Sanatan Dharam Mandir, New Delhi 110048, India. By visiting our site, you are agreeing to be bound by the following terms and conditions. Please read these terms and conditions before using, or submitting content in any form or medium for publication on, Sportzcraazy.com. We may change these terms and conditions at any time. Your continued use of sportzcraazy.com implies that you accept any new or modified terms and conditions that we come up with. Please re-visit the &apos;Terms of Use&apos; link at our site from time to time to stay updated with any changes that we may introduce.</p>
            <p className='text-black/50 leading-[30px]'>If you do not agree with any of the terms and conditions stipulated under this Terms of Use document, you must immediately cease accessing and using the Sportzcraazy website.</p>
            <p className='text-black/50 leading-[30px]'>The terms sportzcraazy.com and Sportzcraazy are used through this entire Terms of Use document to refer to the website, the Company and the employees, associates and affiliates of the Company.</p>

            <h1 className='text-[18px] mt-5 mb-3'>1. REGISTRATION</h1>
            <p className='text-black/50 leading-[30px]'>a. You can browse Sportzcraazy.com without registering for a Sportzcraazy account. In order to post any User Content or access certain features of the website, however, you must register for an account with Sportzcraazy (which may include connecting to Sportzcraazy.com through a third-party service) and select a password and screen name (&quot;Sportzcraazy User ID&quot;). You may not select or use as a Sportzcraazy User ID any name that we determine to be offensive, vulgar or obscene. Sportzcraazy reserves the right to refuse registration of, or cancel a Sportzcraazy User ID or a User account at its sole discretion. By registering, you certify that all information you provide, now or in the future, is accurate. We reserve the right to reclaim Sportzcraazy User IDs on behalf of businesses or individuals that hold legal claim or trademark on those usernames. You are responsible for maintaining the confidentiality of your Sportzcraazy password. By connecting to Sportzcraazy.com with a third-party service like Facebook, you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials for that service.</p>
            <p className='text-black/50 leading-[30px]'>b. You are solely responsible for the activity that occurs on or through your account, and you must keep your account password secure. You must notify Sportzcraazy immediately of any breach of security or unauthorized use of your account. Sportzcraazy will not be liable for your losses caused by any unauthorized use of your account, and you shall be solely liable for the losses of Sportzcraazy or others due to such unauthorized use.</p>
            <p className='text-black/50 leading-[30px]'>c. By registering, you agree to get periodic newsletters and other email notifications.</p>

            <h1 className='text-[18px] mt-4 mb-3'>2. LICENSE</h1>
            <p className='text-black/50 leading-[30px]'>a. Sportzcraazy hereby grants you a limited, revocable, non-exclusive, non-assignable and non-transferable license to access Sportzcraazy.com provided and expressly conditioned upon your agreement that all such access and use shall be governed by all of the terms and conditions set forth in this User Agreement.</p>

            <h1 className='text-[18px] mt-4 mb-3'>3. CONTENT</h1>
            <p className='text-black/50 leading-[30px]'>a. Your responsibility for your content: By uploading, posting, submitting or otherwise disclosing or distributing User Content, you represent and warrant that you own all rights in your User Content and that any User Content you post does not and will not violate third-party rights of any kind, including without limitation any Intellectual Property Rights (defined below) or rights of publicity or privacy. Sportzcraazy reserves the right, but is not obligated, to reject and/or remove any User Content that we believe, in our sole discretion, violates these provisions. Sportzcraazy takes no responsibility and assumes no liability for any User Content that you or any other Users or third parties post or send on Sportzcraazy.com. You understand and agree that any loss or damage of any kind that occurs as a result of the use of any User Content that you send, upload, download, post, transmit, display, or otherwise make available or access through your use of Sportzcraazy.com, is solely your responsibility, and you agree that we are only acting as a passive conduit for your online distribution and publication of your User Content. Sportzcraazy is not responsible for any public display or misuse of your User Content. You understand and acknowledge that you may be exposed to User Content that is inaccurate, offensive, indecent, or objectionable, and you agree that Sportzcraazy shall not be liable for any damages you allege to incur as a result of such User Content.</p>
            <p className='text-black/50 leading-[30px]'>b. Definition of Intellectual Property Rights: For the purposes of this Agreement, &quot;Intellectual Property Rights&quot; means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any state, country, territory or other jurisdiction.</p>

            <h1 className='text-[18px] mt-4 mb-3'>4. COPYRIGHT</h1>
            <p className='text-black/50 leading-[30px]'>a. The Sportzcraazy website (including all text, photographs, graphics, video and audio content contained on our site) is protected by copyright as a collective work or compilation under the copyright laws of India and other countries, and we (subject to the rights of our licensors and licensees under applicable agreements, understandings and arrangements) have all rights therein. All individual articles, blogs, videos, content and other elements comprising our site are also copyrighted works, and we (subject to the rights of our licensors and licensees under applicable agreements, understandings and arrangements) have all rights therein. You must abide by all additional copyright notices or restrictions contained on our site.</p>
            <p className='text-black/50 leading-[30px]'>b. By posting or submitting User Content on or to our site (regardless of the form or medium with respect to such content, whether text, videos, photographs, audio or otherwise), you are giving us, and our affiliates, agents and third party contractors the right to display or publish such content on our site and its affiliated publications (either in the form submitted or in the form of a derivative or adapted work), to store such content, and to distribute such content and use such content for promotional and marketing purposes.</p>
            <p className='text-black/50 leading-[30px]'>c. You shall be solely responsible for your own submissions and the consequences of posting or publishing them. In connection with each of your submissions, you affirm, represent, and/or warrant that: (I) you own or have the necessary licenses, rights, consents, and permissions to use and authorize us to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all such submissions to enable inclusion and use of such submissions in the manner contemplated by us and these Terms and Conditions; and (II) you have the written consent, release, and/or permission of each and every identifiable individual person in such submissions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of such submissions in the manner contemplated by us and these Terms and Conditions. In furtherance of the foregoing, you agree that you will not: (I) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant us all of the rights granted herein; (II) publish falsehoods or misrepresentations that could damage us or any third party; (III) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; or (IV) post advertisements or solicitations of business. We reserve the right to remove or not publish submissions without prior notice. You understand that when you submit content in any form to Sportzcraazy.com we may authorize such content to be distributed or syndicated to or published on other Sportzcraazy-branded environments.</p>
            <p className='text-black/50 leading-[30px]'>d. Unless expressly permitted, you may not copy, reproduce, distribute, publish, enter into a database, display, perform, modify, create derivative works from, transmit or in any way exploit any part of Sportzcraazy.com or any content thereon, except as permitted under the last sentence of this Section 3(d) and except that you may make one print copy that is limited to occasional articles of personal interest only. Without limiting the generality of the foregoing (but subject to the last sentence of this Section 3(d)), you may not distribute any part of this site or any content thereon over any network, including, without limitation, a local area network, or sell or offer it for sale. In addition, these files may not be used to construct any kind of database. Just as we, from time to time, excerpt materials from other sources in order to support the various commentaries and writings contained herein, we respect the right of others to make “fair use” of the materials contained on our site; accordingly, you may from time-to-time excerpt and use materials set forth on this site consistent with the principles of “fair use”.</p>
            <p className='text-black/50 leading-[30px]'>e. We are concerned about the integrity of Sportzcraazy.com when it is viewed in a setting created by a third party that includes advertising or other materials that we have not authorized to be displayed with the content of our site. Neither you nor any third party shall make use of the contents of Sportzcraazy.com in any manner that constitutes an infringement of our rights, including copyright or that has not been authorized by us.</p>

            <h1 className='text-[18px] mt-4 mb-3'>5. RESTRICTIONS ON USE</h1>
            <p className='text-black/50 leading-[30px]'>a. The Sportzcraazy website contains material which is derived in whole or in part from material supplied by the Company, its group companies, various news agencies and other sources (including content partners), and is protected by international copyright and trademark laws. The restrictions on use of the material and content on the Sportzcraazy website by the Subscriber are specified below. Except where specifically authorised, the Subscriber may not modify, copy, reproduce, republish, upload, post, transmit or distribute in any way any material from the Sportzcraazy websites including code and software.</p>
            <p className='text-black/50 leading-[30px]'>b. By using the Sportzcraazy website (other than to read this Agreement for the first time), Subscriber agrees to comply with all of the terms and conditions hereof. The right to use the Sportzcraazy website is personal to Subscriber and is not transferable to any other person or entity. Subscriber is responsible for all use of Subscriber&apos;s Account (under any screen name or password) and for ensuring that all use of Subscriber&apos;s Account complies fully with the provisions of this Agreement. Subscriber shall be responsible for protecting the confidentiality of Subscriber&apos;s password(s), if any.</p>
            <p className='text-black/50 leading-[30px]'>c. The Company shall have the right at any time to change or discontinue any aspect or feature of the Sportzcraazy website, including, but not limited to, content, hours of availability and equipment needed for access or use.</p>

            <h1 className='text-[18px] mt-4 mb-3'>6. DELAYS IN SERVICES</h1>
            <p className='text-black/50 leading-[30px]'>a. Sportzcraazy (including its and their directors, employees, affiliates, agents, representatives or subcontractors) shall not be liable for any loss or liability resulting, directly or indirectly, from delays or interruptions due to electronic or mechanical equipment failures, telephone interconnect problems, defects, weather, strikes, walkouts, fire, acts of God, riots, armed conflicts, acts of war, or other like causes. Sportzcraazy shall have no responsibility to provide you access to Sportzcraazy.com while interruption of Sportzcraazy.com due to any such cause continues.</p>

            <h1 className='text-[18px] mt-4 mb-3'>7. USE OF DISCUSSION THREADS, COMMENTS AND OTHER COMMUNICATION FORUMS</h1>
            <p className='text-black/50 leading-[30px]'>a. If this website contains discussion threads, comment portals, or other message or communication facilities (collectively, &quot;Forums&quot;), you agree to use the Forums only to send and receive messages and material that are proper and related to the particular Forum. By way of example, and not as a limitation, you agree that when using a Forum, you shall not do any of the following:</p>
            <div className='ps-4'>
                <p className='text-black/50 leading-[30px]'>i. Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</p>
                <p className='text-black/50 leading-[30px]'>ii. Publish, post, distribute or disseminate any defamatory, infringing, obscene, indecent or unlawful material or information.</p>
                <p className='text-black/50 leading-[30px]'>iii. Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents.</p>
                <p className='text-black/50 leading-[30px]'>iv. Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another’s computer.</p>
                <p className='text-black/50 leading-[30px]'>v. Conduct or forward surveys, contests, or chain letters.</p>
                <p className='text-black/50 leading-[30px]'>vi. Download any file posted by another user of a Forum that you know, or reasonably should know, cannot be legally distributed in such manner.</p>
            </div>

            <h1 className='text-[18px] mt-4 mb-3'>8. USER CONDUCT</h1>
            <p className='text-black/50 leading-[30px]'>a. You shall use the Sportzcraazy website for lawful purposes only. You shall not post or transmit through the Sportzcraazy website any material which violates or infringes in any way upon the rights of others, which is unlawful, threatening, abusive, defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane or otherwise objectionable, which encourages conduct that would constitute a criminal offence, give right to civil liability or otherwise violate any law, or which, without the Company&apos;s express prior approval, contains advertising or any solicitation with respect to products or services. Any conduct by you that in the Company&apos;s discretion restricts or inhibits others from using or enjoying the Sportzcraazy website will not be permitted. You shall not use the Sportzcraazy website to advertise or perform any commercial solicitation, including, but not limited to, the solicitation of users to become subscribers of other on-line information services competitive with the Sportzcraazy website. The Sportzcraazy website contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music or sound, and the entire contents of the Sportzcraazy website are copyrighted as a collective or severable work under applicable copyright laws. The Company and/or its affiliates own or have acquired a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. You may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. Except as otherwise expressly permitted under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material will be permitted without the express permission of the Company and the copyright owner. In the event of any permitted copying, redistribution or publication of copyrighted material, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made. You acknowledge that you do not acquire any ownership rights by downloading copyrighted material.</p>
            <p className='text-black/50 leading-[30px]'>b. You shall not upload, post or otherwise make available on Sportzcraazy website any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right and the burden of determining that any material is not protected by copyright rests with Subscriber. You shall be solely liable for any damage resulting from any infringement of copyrights, proprietary rights, or any other harm resulting from such a submission. By submitting material to any public area of the Sportzcraazy website, you automatically grants, or warrants that the owner of such material has expressly granted the Company the royalty free, perpetual, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed for the full term of any copyright that may exist in such material. You also permit others to access, view, store or reproduce the material for their personal use. You hereby grant the Company the right to edit, copy, publish and distribute any material made available on the Sportzcraazy website by you.</p>
            <p className='text-black/50 leading-[30px]'>c. The foregoing provisions are for the benefit of the Company, its subsidiaries, affiliates and its third-party content providers and licensors and each shall have the right to assert and enforce such provisions directly or on its own behalf.</p>

            <h1 className='text-[18px] mt-4 mb-3'>9. DISCLAIMER</h1>
            <p className='text-black/50 leading-[30px]'>a. You expressly agree that the use of the website is at your sole risk.</p>
            <p className='text-black/50 leading-[30px]'>b. Neither the Company, its affiliates nor any of their respective employees, agents, third party content providers or licensors warrant that the Sportzcraazy website will be uninterrupted or error free; nor do they make any warranty as to the results that may be obtained from use of the Sportzcraazy website, or as to the accuracy, reliability or content of any information, service, or merchandise provided through the Sportzcraazy website.</p>
            <p className='text-black/50 leading-[30px]'>c. The Sportzcraazy website is provided on an &apos;As Is&apos; basis without warranties of any kind, either express or implied, including, but not limited to, warranties of title or implied warranties of merchantability or fitness for a particular purpose, other than those warranties which are implied by and incapable of exclusion, restriction or modification under the laws applicable to this agreement.</p>
            <p className='text-black/50 leading-[30px]'>d. This disclaimer of liability applies to any loss, damages or injury, caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortious behaviour, negligence, or under any other cause of action. You specifically acknowledge that the Company is not liable for the defamatory, offensive or illegal conduct of other subscribers or third-parties in cases including but not limited to any interactive communication on or through the sites and that the risk of injury from the foregoing rests entirely with subscriber(s).</p>
            <p className='text-black/50 leading-[30px]'>e. In no event will the Company, or any person or entity involved in creating, producing or distributing the Sportzcraazy website or the Sportzcraazy website software, be liable for any damages, including, without limitation, direct, indirect, incidental, special, consequential or punitive damages arising out of the use of or inability to use the Sportzcraazy website. You hereby acknowledge that the provisions of this section shall apply to all content on the Sportzcraazy website.</p>
            <p className='text-black/50 leading-[30px]'>f. In addition to the terms set forth above neither, the Company, nor its affiliates, information providers or content partners shall be liable regardless of the cause or duration, for any errors, inaccuracies, omissions, or other defects in, or untimeliness or unauthenticity of, the information contained within the Sportzcraazy website, or for any delay or interruption in the transmission thereof to the user, or for any claims or losses arising therefrom or occasioned thereby. None of the foregoing parties shall be liable for any third-party claims or losses of any nature, including, but not limited to, lost profits, punitive or consequential damages. Prior to the execution of a stock trade, you are advised to consult with your broker or other financial representative to verify pricing or other information. The Company, its affiliates, information providers or content partners shall have no liability for investment decisions based on any information provided on the Sportzcraazy website. Neither, the Company, nor its affiliates, information providers or content partners warrant or guarantee the timeliness, sequence, accuracy or completeness of this information.</p>
            <p className='text-black/50 leading-[30px]'>g. The Sportzcraazy website contains a variety of content, including articles, blogs, opinions, and user-generated posts. The views and opinions expressed on this website are solely those of the individual authors and contributors and do not necessarily reflect the official stance or beliefs of the Company.</p>
            <p className='text-black/50 leading-[30px]'>h. The information provided on this website is for general informational purposes only. While we strive to ensure the accuracy, completeness, and timeliness of the information presented, we make no representations or warranties of any kind, express or implied, about the reliability, suitability, or availability of the content.</p>
            <p className='text-black/50 leading-[30px]'>i. Any reliance you place on the information provided on the Sportzcraazy website is strictly at your own risk. We shall not be liable for any loss or damage, including but not limited to indirect or consequential loss or damage, arising from the use of this website or any linked external sources.</p>
            <p className='text-black/50 leading-[30px]'>j. The content posted on the Sportzcraazy website may cover a wide range of topics and may include discussions about various products, services, or organizations. Such mentions or references do not constitute an endorsement or recommendation by the Company, unless explicitly stated.</p>
            <p className='text-black/50 leading-[30px]'>k. External links to third-party websites are included on the Sportzcraazy website for informational purposes and convenience. We do not endorse the content or views expressed on external websites and are not responsible for their content, practices, or policies.</p>
            <p className='text-black/50 leading-[30px]'>l. The content published on the Sportzcraazy website is protected by copyright law. Any unauthorized use or reproduction of the materials on this website without prior written consent from SPORTZCRAAZY may violate copyright laws.</p>

            <h1 className='text-[18px] mt-4 mb-3'>10. INDEMNIFICATION</h1>
            <p className='text-black/50 leading-[30px]'>a. You shall indemnify, defend and hold the Company (including its officers, directors, employees, affiliates, group companies, agents, representatives or subcontractors) harmless from any and all claims and losses imposed on, incurred by or asserted as a result of or related to: (a) your access and use of Sportzcraazy.com (b) any non-compliance by user with the terms and conditions hereof; or (c) any third party actions related to user&apos;s receipt and use of the information, whether authorized or unauthorized. Any clause declared invalid shall be deemed severable and shall not affect the validity or enforceability of the remainder. These terms may only be amended in a writing signed by Sportzcraazy.</p>
            
            <h1 className='text-[18px] mt-4 mb-3'>11. CONFLICTING TERMS</h1>
            <p className='text-black/50 leading-[30px]'>a. If there is any conflict between this User Agreement and other documents, this User Agreement shall govern, whether such order or other documents are prior to or subsequent to this User Agreement, or are signed or acknowledged by any director, officer, employee, representative or agent of Sportzcraazy.</p>

            <h1 className='text-[18px] mt-4 mb-3'>12. ENTIRE AGREEMENT</h1>
            <p className='text-black/50 leading-[30px]'>a. This User Agreement constitutes the entire agreement between the parties, and no other agreement, written or oral, exists between you and Sportzcraazy. By using the information on Sportzcraazy.com, you assume full responsibility for any and all gains and losses, financial, emotional or otherwise, experienced, suffered or incurred by you.</p>

            <h1 className='text-[18px] mt-4 mb-3'>13. TERMINATION</h1>
            <p className='text-black/50 leading-[30px]'>a. This User Agreement and the license rights granted hereunder shall remain in full force and effect unless terminated or cancelled for any of the following reasons: (a) immediately by Sportzcraazy for any unauthorized access or use by you (b) immediately by Sportzcraazy if you assign or transfer (or attempt the same) any rights granted to you under this Agreement; (c) immediately, if you violate any of the other terms and conditions of this User Agreement. Termination or cancellation of this Agreement shall not effect any right or relief to which Sportzcraazy may be entitled, at law or in equity. Upon termination of this User Agreement, all rights granted to you will terminate and revert to Sportzcraazy. Except as set forth herein, regardless of the reason for cancellation or termination of this User Agreement, the fee charged if any for access to Sportzcraazy.com is non-refundable for any reason.</p>

            <h1 className='text-[18px] mt-4 mb-3'>14. JURISDICTION</h1>
            <p className='text-black/50 leading-[30px]'>a. The terms of this agreement are exclusively based on and subject to Indian law. You hereby consent to the exclusive jurisdiction and venue of courts in Bangalore, India in all disputes arising out of or relating to the use of this website. Use of this website is unauthorized in any jurisdiction that does not give effect to all provisions of these terms and conditions, including without limitation this paragraph.</p>
            <p className='text-black/50 leading-[30px]'>b. The above terms of use apply to all of Sportzcraazy&apos;s platforms, including the mobile apps for Android, Windows and iOS.</p>
        </div>
    )
}

export default TermsOfUse